In [1]:
import numpy as np
from nltk.corpus import stopwords
from nltk import word_tokenize,download
import string
#download()

In [22]:
with open("test.ft.txt", 'r',encoding="utf-8") as f:
    for line in f:
        content = line
# you may also want to remove whitespace characters like `\n` at the end of each line
#content = [x.strip().split(" ") for x in content] 

delete = """"stopwords.words('english')+"""" list(string.punctuation)+["''",'``',"``"]
tokenizedContent = []
for sentece in content:
    sentArr = [word for word in word_tokenize(sentece.lower()) if word not in delete and '\'' not in word]    
    tokenizedContent.append(sentArr)

Y = [x[0] for x in tokenizedContent]
X = [x[1:] for x in tokenizedContent]

In [20]:
Y

['__label__2', '__label__2', '__label__1', '__label__2', '__label__2']

In [21]:
X[0]

['great',
 'cd',
 'lovely',
 'pat',
 'one',
 'great',
 'voices',
 'generation',
 'listened',
 'cd',
 'years',
 'still',
 'love',
 'good',
 'mood',
 'makes',
 'feel',
 'better',
 'bad',
 'mood',
 'evaporates',
 'like',
 'sugar',
 'rain',
 'cd',
 'oozes',
 'life',
 'vocals',
 'jusat',
 'stuunning',
 'lyrics',
 'kill',
 'one',
 'life',
 'hidden',
 'gems',
 'desert',
 'isle',
 'cd',
 'book',
 'never',
 'made',
 'big',
 'beyond',
 'everytime',
 'play',
 'matter',
 'black',
 'white',
 'young',
 'old',
 'male',
 'female',
 'everybody',
 'says',
 'one',
 'thing',
 'singing']

In [5]:
lengths = [len(x) for x in X]


In [6]:
max(lengths)

230

In [7]:
min(lengths)

6

In [8]:
np.histogram(lengths)

(array([40217, 91540, 79731, 60551, 46965, 36532, 26293, 15930,  2220,    21], dtype=int64),
 array([   6. ,   28.4,   50.8,   73.2,   95.6,  118. ,  140.4,  162.8,
         185.2,  207.6,  230. ]))

In [9]:
len(content)

400000

In [10]:
HitMap ={}
IndexMap ={}
for i in range(0,len(lengths)):
    value = lengths[i]
    if value not in HitMap:
        IndexMap[value]=[]
        HitMap[value]=0
    HitMap[value]+=1
    IndexMap[value].append(i)
HitMap

{6: 1,
 8: 4,
 10: 1,
 11: 3,
 12: 5,
 13: 20,
 14: 36,
 15: 102,
 16: 244,
 17: 511,
 18: 850,
 19: 1283,
 20: 1703,
 21: 2817,
 22: 4084,
 23: 4475,
 24: 4795,
 25: 4834,
 26: 4958,
 27: 4804,
 28: 4687,
 29: 4603,
 30: 4520,
 31: 4552,
 32: 4394,
 33: 4397,
 34: 4186,
 35: 4316,
 36: 4365,
 37: 4312,
 38: 4199,
 39: 4086,
 40: 4118,
 41: 4028,
 42: 3956,
 43: 3955,
 44: 3963,
 45: 3993,
 46: 3971,
 47: 4013,
 48: 3912,
 49: 3809,
 50: 3892,
 51: 3818,
 52: 3685,
 53: 3631,
 54: 3701,
 55: 3541,
 56: 3581,
 57: 3490,
 58: 3702,
 59: 3400,
 60: 3605,
 61: 3512,
 62: 3519,
 63: 3425,
 64: 3487,
 65: 3406,
 66: 3409,
 67: 3354,
 68: 3318,
 69: 3291,
 70: 3358,
 71: 3228,
 72: 3169,
 73: 3101,
 74: 2998,
 75: 3037,
 76: 3017,
 77: 2859,
 78: 2924,
 79: 2897,
 80: 2888,
 81: 2833,
 82: 2833,
 83: 2805,
 84: 2700,
 85: 2773,
 86: 2703,
 87: 2631,
 88: 2634,
 89: 2727,
 90: 2601,
 91: 2596,
 92: 2591,
 93: 2533,
 94: 2426,
 95: 2545,
 96: 2366,
 97: 2478,
 98: 2367,
 99: 2352,
 100: 2366,
 

In [11]:
def equalLength(k,max,min):
    dataSize = max-min
    if dataSize<=0:
        buckets = set()
        buckets.add(1)
        return buckets
    
    bucketSize= dataSize/k
    currBucket=min
    #buckets = {}
    buckets = set()
    while currBucket<= max:
        #buckets[currBucket]=[]
        buckets.add(currBucket)
        currBucket+=bucketSize+1
        
    if currBucket == max:
        #buckets[max+1]=[]
        buckets.add(currBucket+1)
        
    #maybe add infinity spot
    return buckets

In [12]:
def equalSize(k,lengths):
    unique = set()
    for length in lengths:
        unique.add(length)
    
    uniqueLength = len(unique)
    uniqueList = list(unique)
    sort(uniqueList)
    
    bucketSize= uniqueLength/k
    currBucket=0
    #buckets = {}
    buckets = set()
    while currBucket<= max:
        #buckets[currBucket]=[]
        buckets.add(uniqueList[currBucket])
        currBucket+=bucketSize
        
    if currBucket == max:
        buckets.add(uniqueList[currBucket+1])
        #buckets[max+1]=[]
    #maybe add infinity spot
    return buckets

In [24]:
def getHistogram(data,partition):
    histogram = [0]*len(partition)
    for dat in data:
        for i in range(0,len(partition)):
            if dat <= partition[i]:
                histogram[i]+=1
                break
        #maybe add infinity spot handler
    return histogram

part = [6,28.4,50.8,73.2,95.6,118,140.4,162.8,185.2,207.6,230]
getHistogram(lengths,part)

[1, 40216, 91540, 79731, 60551, 48763, 34734, 26293, 15930, 2220, 21]

In [ ]:
(array([40217, 91540, 79731, 60551, 46965, 36532, 26293, 15930,  2220,    21], dtype=int64),
 array([   6. ,   28.4,   50.8,   73.2,   95.6,  118. ,  140.4,  162.8,
         185.2,  207.6,  230. ]))