In [16]:
#imports
from gensim import corpora, models, similarities
import numpy as np
from gensim.models import KeyedVectors
#from gensim.test.utils import common_texts

In [5]:
#constants
NUMOFSENTENCES=0
VECTSIZE = 4
ALPH = 0.025
MINCOUNT=0
EPOCH=100
MAXDIST=5
MINCOUNT=1
THREADS=1

In [56]:
#common_texts[0]

['human', 'interface', 'computer']

In [57]:
#data
assummedinput = [('big boobs',1),('small penis',-1)]
array = np.array(assummedinput)
NUMOFSENTENCES = len(array)
sentences = array[:,0]
splittedSentences = []
for sentence in sentences:
    splittedSentences.extend([sentence.split(' ')])
labels =  array[:,1]
uniqueWords={}
for sentence in sentences:
    for word in sentence:
        cleanedWord = word
        uniqueWords[cleanedWord]=0
splittedSentences

[['big', 'boobs'], ['small', 'penis']]

In [78]:
#model = models.Word2Vec(splittedSentences,size=VECTSIZE,window=MAXDIST,min_count=MINCOUNT,workers=THREADS)
#model.train([['boobs','penis'],['boobs','boobs']],total_examples=NUMOFSENTENCES,epochs=EPOCH)
model = models.Word2Vec(splittedSentences,size=VECTSIZE,window=MAXDIST,min_count=MINCOUNT,workers=THREADS,iter=EPOCH)
for word in model.wv.vocab:
    print(word)
    print(model.wv[word])

big
[ 0.03352055 -0.1096281   0.11912877 -0.00512887]
boobs
[ 0.02671231 -0.09381433 -0.01722193 -0.03024457]
penis
[-0.11391054  0.06208725 -0.12395608 -0.11756784]
small
[ 0.00989503  0.0254954  -0.11239155  0.07433815]


In [ ]:
#from work
it = 'need to fill this with iterator'
model = models.Word2Vec(size=VECTSIZE, min_count=MINCOUNT, alpha=ALPH)
model.build_vocab(it)
for epoch in range(EPOCH):
    model.train(it,total_ecamples=model.corpus_count,epochs=model.iter)
    model.alpha -= 0.002
    model.min_alpha = model.alpha

In [2]:

with open("test.ft.txt", 'r',encoding="utf-8") as f:
    content = f.readlines()
content = [x.strip().split(" ") for x in content] 

Y = [x[0] for x in content]
X = [x[1:] for x in content]

In [5]:
def gensimW2V(tokenizedSenteces,VECTSIZE = 300,ALPH = 0.025,MINCOUNT=0,EPOCH=100,MAXDIST=5,THREADS=1):
    model = models.Word2Vec(tokenizedSenteces,size=VECTSIZE,window=MAXDIST,min_count=MINCOUNT,workers=THREADS,iter=EPOCH)
    return model

m=gensimW2V(X,1000,0.002,5,50,1,1)

In [6]:
m.save('w2v')

In [20]:
m.wv.save('the vecots')
wv = KeyedVectors.load("the vecots", mmap='r')

In [22]:
m[wv.index2word[0]]

C:\Users\Elad-PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-6.31534830e-02, -9.28809773e-03,  2.35790521e-01,  1.02966554e-01,
        1.90987200e-01, -8.67650807e-02, -1.50122002e-01,  2.59012934e-02,
       -7.63386395e-03, -4.32576507e-01, -4.57278639e-02, -3.37143213e-01,
        1.20071694e-01,  1.74264207e-01,  4.12594140e-01, -2.88769066e-01,
        4.65495661e-02, -1.20342702e-01, -1.34615935e-02,  2.85789490e-01,
        3.29828709e-01,  7.60387257e-02, -3.64494890e-01, -9.96457785e-02,
        3.13073456e-01,  5.72017431e-02,  2.29945436e-01, -1.97067514e-01,
        1.13906331e-01,  1.71127811e-01, -1.75651051e-02, -1.90440744e-01,
       -6.64200783e-02, -2.38095567e-01, -2.75838941e-01, -1.50325716e-01,
       -9.64341685e-04,  1.41492799e-01, -3.57587822e-02,  4.26799089e-01,
       -2.46167794e-01,  4.75676381e-04, -1.66097805e-01,  2.30458558e-01,
       -1.00968227e-01,  1.70630142e-01, -2.96217710e-01, -3.85829389e-01,
       -1.77815109e-01,  1.50306910e-01,  3.45787704e-01, -5.10209858e-01,
       -3.86423409e-01,  

In [23]:
len(wv.vocab)

142105